[package]
name = "github-stats"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
anyhow = "1.0.86"
config = "0.14.0"
dotenv = "0.15.0"
env_logger = "0.11.3"
log = "0.4.22"
mime = "0.3.17"
openssl = { version = "0.10.64", features = ["vendored"] }
reqwest = { version = "0.12.5", features = ["json"] }
serde = "1.0.203"
serde_json = "1.0.120"
tokio = "1.38.0"
url = "2.5.2"
