services:
  github-stats:
    container_name: github-stats
    build:
      context: .
      dockerfile: Containerfile
      args:
        STATS_PORT: ${STATS_PORT:-8080}
    env_file: .env
    ports:
      - "3001:${STATS_PORT:-8080}"
